### ISSUE TITLE
Darktheme chat request

### ISSUE THREAD

**Issue by Deph0** [martink635/twitchls#25]
Would like to have darktheme chat, as I have twitch.com toggled to darktheme.

I did a quick search, it looks like you can get the embedded version of the chat by adding ?darkpopout to the end of the url, e.g. http://www.twitch.tv/embed/channel_name/chat?darkpopout

This can probably be a setting in the website to toggle or somehow get the information from twitch if the user has darktheme toggled or not.

**Comment by mkoterle** [comment]
Hello, we have a new design incoming, with the change to the new API, it will have a dark theme, but I do not think it will be this month, probably sometime in October :)

I will try and push the fix for the new API this weekend, so we don't have downtimes.

**Comment by mkoterle** [comment]
Migrated to v5, it was easier than I thought, site is back online.

**Comment by wili111** [comment]
Where can i find the dark theme setting? (my settings page looks like this https://i.imgur.com/DEpxrut.png )

Maybe settings support is not yet implemented for Firefox?

**Comment by haka3l** [comment]
Same no darktheme option. Can use night eye chrome extension for now, tho it doesn't look the same.

**Comment by MatthewRatajczyk** [comment]
You can kind a use FrankerFaceZ and set it dark, but the only issue there is that for some reason the chat box isn't the same as the chat so the text there still acts like twitch is in light mode. You can just write a style="color:white" 
https://media.discordapp.net/attachments/538255779279536128/776604938884087818/unknown.png?width=1443&height=442

Do they plan to add there own dark theme or get it working fully with FrankerFaceZ?

**Comment by thundron** [comment]
I made an extension that adds the required `&darkpopout` to the embed char url, although you need to reload the channel page for it to work as for some reason, the change to a channel page doesn't trigger a popstate event in any way, not sure how to attach to the vuejs router from the outside either. I can add the zip here, it can be as little as 4 lines of code if you strip the 'popstate' event handler

**Comment by arrowgent** [comment]
use midnight lizard extension for all the internet to be darkmode.
rarely problems exist where images will be "darkmode" inverted. (not on twitchls)

**Comment by Deph0** [comment]
While all the suggestions here about browser extensions are interesting, they have no place in this issue- as it does not help to implement darktheme into the website, but dilute the issue. I thank you for your interest however, and welcome your other suggestions. 

While I'm not interested enough to fix it myself by creating a PR (time constraints of my own life), i did go ahead and confirm that it would work by adding `darkpopout` to the url for the chat, using inspect tool. 

It'd be nice to have this as a setting, if not- I've located the place where you would add it to the url, to get it permanently. 
[resources/assets/js/components/Stream.vue#L41](https://github.com/martink635/twitchls/blob/95538050a5f80a87be1262f8b233a57926b325d0/resources/assets/js/components/Stream.vue#L41)

**Comment by thundron** [comment]
I'm not sure how to install composer as I'm more accustomed to working on *nix systems, otherwise I'd give it a try at implementing a settings menu/page/modal/button/whatever to hold the dark-mode switch (which might as well apply to all the pages, not just the stream chat, using the same colors of twitch dark mode without too much sugar)

**Comment by martink635** [comment]
Hello everyone, sadly the new design is halfway done as I am swamped with projects right now. I will just add an option in the settings for the dark chat in the current site (and that it automatically sets it if you have a dark theme one)

I will let you know in here when it's done (sometime this weekend)

**Comment by thundron** [comment]
@martink635 it's ok, I might as well give it a try on building on wsl2 if you don't mind and agree that it should be a check in the already implemented settings page

**Comment by thundron** [comment]
what version of nodejs + npm shall I use?

**Comment by martink635** [comment]
@thundron Node 10 should probably be ok for the master branch

Pushed the new design on the _next_ branch. It's available to preview here: https://next.twitchls.com/
Let me know if everything is ok (search is missing). Dark mode is triggered automatically if your system is set to dark mode. I will add an additional option to toggle/force it.

**Comment by martink635** [comment]
Next is now on produciton, so closing this one. Feel free to open a new one if you have any problems.
