### ISSUE TITLE
Support for raid request

### ISSUE THREAD

**Issue by Leojnv** [martink635/twitchls#30]
Would be nice for twitchls to auto change channels when a raid happens, so no need for change link manually.

**Comment by martink635** [comment]
It would be a lovely feature to have, but I don't think it's possible right now. We are just embeding the iframe and I don't get any event to change the actual stream source. Using the Twitch SDK would probably make this possible but would also make the watching experience same as on Twitch.tv

I am closing it for now, feel free to comment/research more on this topic, and reopen if you feel it's appropriate.
