### ISSUE TITLE
Feature Request: Add a channel selector on the left

### ISSUE THREAD

**Issue by pxia** [martink635/twitchls#31]
This is one of the features I miss from twitch.tv. A list of followed channels that are live would be very useful for channel hopping.

**Comment by martink635** [comment]
Interesting one!

I guess that you want a list of the followed streams while watching another stream? Did I get that right?

If so, this viewer defaults to a similar setup as the "theatre mode" on Twitch (with some added benefits as resizable chat and fullscreen with chat option), which is primarily focused on the stream watching experience. I might think about adding this so it's not shown by default and toggle-able, so it doesn't take space all the time. I want to avoid adding a lot of buttons on the stream watching page.

**Comment by pxia** [comment]
Yes, Toggle-able sounds good to me! I think it's best implemented in a way that when you change change channels you don't refresh the page, so you don't have to re-toggle it.

**Comment by hotpxl** [comment]
Second this. A followed stream list is all I need to fully replace twitch.

**Comment by martink635** [comment]
Pushed this feature on https://next.twitchls.com/settings, it's disabled by default

Currently it doesn't show the user avatar, but the stream in the tiny image.

**Comment by martink635** [comment]
Next is now on produciton, so closing this one. Feel free to open a new one if you have any problems.
