### ISSUE TITLE
Dragging window from one to a different resolution montitor screws up the proportions

### ISSUE THREAD

**Issue by Akip25** [martink635/twitchls#32]
Would be really cool if you could add the chat size slider as a proportion of displayable screen.

I got a 1440p main screen and a 1080p other monitor, if I drag the window from one to the other the proportions break up. 
![viewport proportions](https://user-images.githubusercontent.com/9020414/100066972-fac08f00-2e35-11eb-961e-4a625764ff9f.jpg)

Desired behavior would be, I give the stream lets say 2/3rds of the bottom length of the screen and chat 1/3rd, I drag the window to the other different resolution monitor and its still 2/3rds and 1/3rd.

**Comment by Akip25** [comment]
hey I just saw this is fixed in https://next.twitchls.com/

cool stuff sorry for bothering

**Comment by martink635** [comment]
No worries, it was bothering me too 🙂

Now it keeps the same width in pixels, instead of position from the left side.
