### ISSUE TITLE
[Feature Request] Start stream with sound enabled, and with quality on source

### ISSUE THREAD

**Issue by Zotikus1001** [martink635/twitchls#35]
Maybe add an option to do this.

I dislike how we have to un-mute the stream every time, and also change the quality settings.

**Comment by martink635** [comment]
Not sure if I can do this, as it automatically sets it (for me its not unmuted and it goes to the highest quality after a couple of seconds). May I ask which OS and browser are you using?

**Comment by martink635** [comment]
Oh and do you have the same issue on https://next.twitchls.com/ ?

**Comment by BrokenSilence** [comment]
> 
> 
> Oh and do you have the same issue on https://next.twitchls.com/ ?

Hi, yes same issue on next, as I've been using it for the dark chat.
I'm using Firefox on Windows 10 v20H2

**Comment by martink635** [comment]
It's highly likely that I can't do much regarding this, I will investigate a bit more

**Comment by BrokenSilence** [comment]
> 
> 
> It's highly likely that I can't do much regarding this, I will investigate a bit more

So, I just found out it was Firefox blocking the audio auto play. So sorry for being dumb. :P 
But I'd still love a way to get it to auto set source quality. 
Hope there's an easier way, I did find a way, but it would require to edit the js script that twitch uses for video embedding.

**Comment by martink635** [comment]
Oh great 👍 

Feel free to paste what you found here :)

The thing is I am not using the Twitch SDK, just using iframes

**Comment by BrokenSilence** [comment]
ye, thats why I said that, cus I believe from what I read that its impossible to change quality with iframe :(

**Comment by BrokenSilence** [comment]
> 
> 
> ye, thats why I said that, cus I believe from what I read that its impossible to change quality with iframe :(

So I found a script for Tempermonkey that does this. 
Added in your website on the "User Includes" in the settings of the script, and its working flawlessly.  :)

Maybe you could implement it on your website somehow? Idk.

Heres the script: https://github.com/nomomo/Twitch-Auto-Max-Quality
