### ISSUE TITLE
Add a www CNAME record

### ISSUE THREAD

**Issue by FrankSalmick** [martink635/twitchls#36]
I usually switch from www.twitch.tv/stream to twitchls.com, but chrome defaults to keeping the www as part of the domain. So I change it to www.twitchls.com/stream which doesn't resolve. Can you add a WWW cname record? I put it in my hosts but I thought I'd ask here for others who don't know how

**Comment by martink635** [comment]
I've added it, it may take several hours to register, and there was a 301 redirect in place before for the www domain.

**Comment by martink635** [comment]
PS: I suggest checking out https://next.twitchls.com/ It will be switched out to the live version this weekend🙂
