### ISSUE TITLE
Followed streamers not appearing

### ISSUE THREAD

**Issue by Rajesus1** [martink635/twitchls#38]
I logged in with Twitch on the updated website, and the followed tab is missing streams that should be showing up.
For example, 19 of the streamers I follow are live, but only 13 show up in the followed tab on Twitchls.
If I go directly to their stream, it works fine; they are just not showing up in the followed listing.
Before the update today, this was not an issue that I had.

**Comment by Nigh7Stalk3r** [comment]
Same issue for me, after the new update it's only showing 8 channels online when i have 25 online on twitch's site.

**Comment by martink635** [comment]
Thanks for reporting this, I'm pretty sure I know what the problem is.

Do you mind sharing the number of follwed streams you have (not online, all of them). As the changes with the new Twitch API, I need to make several calls to get the followed streams, previously it was just one 🙂

**Comment by Nigh7Stalk3r** [comment]
> Thanks for reporting this, I'm pretty sure I know what the problem is.
> 
> Do you mind sharing the number of follwed streams you have (not online, all of them). As the changes with the new Twitch API, I need to make several calls to get the followed streams, previously it was just one 🙂

241

**Comment by Rajesus1** [comment]
151

**Comment by Rajesus1** [comment]
> Thanks for reporting this, I'm pretty sure I know what the problem is.
> 
> Do you mind sharing the number of follwed streams you have (not online, all of them). As the changes with the new Twitch API, I need to make several calls to get the followed streams, previously it was just one 🙂

151

**Comment by martink635** [comment]
Thanks for sharing, definetly was not expecting such numbers, will rework this soon(ish) and report back here

**Comment by martink635** [comment]
Now it should load the first 100 online followed streams at once. Please report back if it's working :)

**Comment by recon88** [comment]
Did you push the fix to the live site already? I'm not seeing a difference.
Twitchls shows 6 followed channels being live, Twitch shows 12.

**Comment by eclipsaa** [comment]
soo this is still a issue.  A few streamers are not showing up on the site.  I can search them and find them using the game category but there not showing up on the follow list.   Kind of wondering if this twitchls is just dead...

**Comment by martink635** [comment]
Not dead 🙂

Can you give a bit more info regarding the issue? How many streams are you following etc. As due to the way the Twitch API works it’s not easy to get all of them.

**Comment by martink635** [comment]
Closed due to inactivity…
