### ISSUE TITLE
Can't play Korean streams through twitchls

### ISSUE THREAD

**Issue by solidtriangle** [martink635/twitchls#39]
It gives me this error in the area where chat is supposed to be displayed: "www.twitch.tv refused to connect."

I just used Twitchls to watch Korean streamers yesterday so I guess the new update caused this? I know most people don't even bother with Korean streams but lmk if it works on your device.

**Comment by martink635** [comment]
I'm pretty sure it's due to some new Twitch API endpoints not behaving like they should. I did a workaround for english based streams which works mostly ok.

Can you please share a stream link that is not working, so I can test out a fix (please copy a twitchls.com link and a twitch.tv link)

**Comment by zerfl** [comment]
An example would be:
Twitch: https://www.twitch.tv/hanryang1125
Twitchls: https://twitchls.com/%ED%92%8D%EC%9B%94%EB%9F%89

They're the same stream. The latter is using the Korean nickname in Hangul while Twitch is (correctly) pointing at the latin username. Using https://twitchls.com/hanryang1125 works. So basically Twitchls is putting the wrong link for certain streams.

**Comment by solidtriangle** [comment]
Yea, the stream above would be a good example and I see it's working with the address with english username.

**Comment by martink635** [comment]
Thanks for providing more information, will report back here as I sort it out

**Comment by martink635** [comment]
This is fixed on the latest version
