### ISSUE TITLE
bugs in twitchls

### ISSUE THREAD

**Issue by bobkelso124** [martink635/twitchls#41]
Hi dev thanks for the wonderful site that allows ads to be bypassed. it means a lot :L) However, there some bugs on the site that going on to the main add filled site does not resolve :L( 

1. Muted streams everytime i load in to a new stream. (this is every stream i go in to even when main add filled site is not muted)

2. auto quality setting for stream viewing. (this setting is just plain stupid, and when ever I change the stream does not matter which stream it is off of this the stupid player jumps right back to it on its own, also for some dumb reason the quality changes when not the main focus please fix this to :L) this was a add filled dumb idea.) 

3. logging in to site after the new changes. (logging in does not keep you logged in major bug here please fix asap)

**Comment by martink635** [comment]
Hey, thanks for reporting,
the ads not showing is not why this was made, it's just that they are not showing for some users. This can change as I am in no control regarding this.

There's an issue already opened for the sound and quality, you can read more about it there: https://github.com/martink635/twitchls/issues/35

Currently you are getting logged out every couple of hours, this is also something I will be updating in the future, so I will be closing this one. Feel free to open a new one if you have more issues.

**Comment by bobkelso124** [comment]
no ads for some? im not using any ad blocker and no ads on here thats something new. i can use the main site and get flooded with them with blocker on or off.

**Comment by martink635** [comment]
I just meant to say, there's nothing that I did specially for the ads to not show up. So this might change and it's out of my scope.
