### ISSUE TITLE
twitch has broken your site by displaying purple screen

### ISSUE THREAD

**Issue by bobkelso124** [martink635/twitchls#47]
he sreen reads close to this.. hi we know you are using a different site or ad blocker for the best twitch experience use the main site.

PLEASE FIND A WAY TO BYPASs THIS :L)

**Comment by bobkelso124** [comment]
also thi purple screen never leaves once it appears no matter what i do.

**Comment by BrokenSilence** [comment]
Sadly, ads are finally here :(
This website never did anything to prevent ads. And there's nothing it can do.
It was simply, that twitch didn't show ads on embedded streams.
Since it's now showing ads, we are doomed :(

I still prefer this website, as it lets me resize the chat, and I love that.



> 
> 
> also thi purple screen never leaves once it appears no matter what i do.

Just wait a while.
The purple screen shows to replace the ad, so it should be gone in 30 sec to 1min.

**Comment by bobkelso124** [comment]
the purple screen stays for me for hours, never leaves no matter what i do.
even after the ads are done on twitch main

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by CaffeinatedBradley** [comment]
Can confirm this issue. Sometimes the stream will automatically start after ~30 seconds but sometimes it just sits on the purple screen. I've attached a screenshot.

https://imgur.com/a/jHkZgOG

**Comment by CaffeinatedBradley** [comment]
Just an update, this is now 3+ months later and this is still occurring making your site borderline unusable. It will sit at this purple screen (screenshot above) in 30 second increments, once it reaches 0 the timer starts back to 30 seconds again and this will continue repeatedly once it occurs. Refreshing does not resolve. Refreshing clean w/ out cookies doesn't resolve. Closing out browser, re-opening and refreshing the stream does not resolve. It only seems to resolve itself over time, 10+ minutes later sometimes.

This is a pretty substantial bug and is substantially affecting the use of twitchls. I'm probably wasting my time testing and typing this if it just falls on deaf ears.

RIP twitchls?

**Comment by martink635** [comment]
This is out of the scope of this project, and not in my control.

This was not meant to bypass ads, just to use a different interface, the ad removal was accidental.
